### ISSUE TITLE
Use cases for Map and Geolocation services/api

### ISSUE THREAD

**Issue by kumarrishav** [OpenIoMeT/Service-crawler#1]
Please define possible use cases for this service. Accordingly, we will consume only those type of API as Google provides 7-8 types of web service api for different purposes.
Source : https://developers.google.com/maps/get-started/ 
@snowmantw  @kaichih

**Comment by kumarrishav** [comment]
I think, this (https://github.com/googlemaps/google-maps-services-js) will do our work. It has rich set of apis. So, no need of shimmer for this i guess.  @snowmantw

**Comment by kumarrishav** [comment]
If we don't need this repo, then i will modify it to iomet-service repository (explained in comment of iomet-testcases repo)

**Comment by kaichih** [comment]
If google-maps-services-js can match our needs, we won't need this repo so far.

**Comment by kumarrishav** [comment]
cool. Thanks

**Comment by kumarrishav** [comment]
geolocation-shimmer renamed to Service-crawler. Thx
